// <auto-generated />
using System;
using LHDTV.Models.DbEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LHDTV.Migrations
{
    [DbContext(typeof(LHDTVContext))]
    [Migration("20200406165642_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LHDTV.Models.DbEntity.FileTags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FolderDbId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FolderDbId");

                    b.ToTable("FileTags");
                });

            modelBuilder.Entity("LHDTV.Models.DbEntity.FolderDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DefaultPhotoId")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DefaultPhotoId");

                    b.HasIndex("UserId");

                    b.ToTable("Folder");
                });

            modelBuilder.Entity("LHDTV.Models.DbEntity.PhotoDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int?>("FolderDbId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RealDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("caption")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("FolderDbId");

                    b.HasIndex("UserId");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("LHDTV.Models.DbEntity.TagDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PhotoDbId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhotoDbId");

                    b.ToTable("TagDb");
                });

            modelBuilder.Entity("LHDTV.Models.DbEntity.TagPropDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("TagDbId")
                        .HasColumnType("int");

                    b.Property<string>("propKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("propVal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TagDbId");

                    b.ToTable("TagPropDb");
                });

            modelBuilder.Entity("LHDTV.Models.DbEntity.UserDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("LHDTV.Models.DbEntity.FileTags", b =>
                {
                    b.HasOne("LHDTV.Models.DbEntity.FolderDb", null)
                        .WithMany("PhotosTags")
                        .HasForeignKey("FolderDbId");
                });

            modelBuilder.Entity("LHDTV.Models.DbEntity.FolderDb", b =>
                {
                    b.HasOne("LHDTV.Models.DbEntity.PhotoDb", "DefaultPhoto")
                        .WithMany()
                        .HasForeignKey("DefaultPhotoId");

                    b.HasOne("LHDTV.Models.DbEntity.UserDb", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("LHDTV.Models.DbEntity.PhotoDb", b =>
                {
                    b.HasOne("LHDTV.Models.DbEntity.FolderDb", null)
                        .WithMany("Photos")
                        .HasForeignKey("FolderDbId");

                    b.HasOne("LHDTV.Models.DbEntity.UserDb", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("LHDTV.Models.DbEntity.TagDb", b =>
                {
                    b.HasOne("LHDTV.Models.DbEntity.PhotoDb", null)
                        .WithMany("Tag")
                        .HasForeignKey("PhotoDbId");
                });

            modelBuilder.Entity("LHDTV.Models.DbEntity.TagPropDb", b =>
                {
                    b.HasOne("LHDTV.Models.DbEntity.TagDb", null)
                        .WithMany("Properties")
                        .HasForeignKey("TagDbId");
                });
#pragma warning restore 612, 618
        }
    }
}
